server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-service
          uri: https://github.com/warriors230/microservices
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
security:
  user:
    name: root
    password: s3cr3t